site_name: Writings
theme:
  name: material

nav:
  - Home: 'index.md'
  - Writings:
    - 'Book Reviews/Discussion':
      - 'Domain Driven Design Quickly': 'book_reviews/domain_driven_design_quickly/overview.md'
    - 'Other Musings': 'other_musings.md'
  - "About Me": "about.md"
